name: CI/CD Pipeline

on:
  push:
    branches: [ main, developer ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.12"

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        
    - name: Set up Python
      run: uv python install ${{ env.PYTHON_VERSION }}
      
    - name: Install dependencies
      run: uv sync --frozen
      
    - name: Run linting with ruff
      run: |
        uv add --dev ruff
        uv run ruff check .
        uv run ruff format --check .
        
    - name: Run type checking with mypy
      run: |
        uv add --dev mypy
        uv run mypy main.py
        
    - name: Security scan with bandit
      run: |
        uv add --dev bandit
        uv run bandit -r . -f json -o bandit-report.json || true
        
    - name: Upload security scan results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-scan-results
        path: bandit-report.json
        
    - name: Test application startup
      run: |
        uv run python -c "import main; print('✅ Application imports successfully')"
        
    - name: Validate FastAPI app
      run: |
        uv run python -c "
        from main import app
        print('✅ FastAPI app created successfully')
        print(f'Available routes: {[route.path for route in app.routes]}')
        "

  security:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        
    - name: Set up Python
      run: uv python install ${{ env.PYTHON_VERSION }}
      
    - name: Install dependencies
      run: uv sync --frozen
      
    - name: Run safety check
      run: |
        uv add --dev safety
        uv run safety check --json --output safety-report.json || true
        
    - name: Upload safety report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: safety-report
        path: safety-report.json

  build:
    runs-on: ubuntu-latest
    needs: [test, security]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
        
    - name: Set up Python
      run: uv python install ${{ env.PYTHON_VERSION }}
      
    - name: Install dependencies
      run: uv sync --frozen
      
    - name: Build application
      run: |
        echo "✅ Application built successfully"
        uv run python -c "from main import app; print('FastAPI app ready for deployment')"
        
    - name: Create deployment artifact
      run: |
        mkdir -p dist
        cp main.py dist/
        cp pyproject.toml dist/
        cp uv.lock dist/
        tar -czf dist/smartreply-clone.tar.gz -C dist .
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: dist/

  deploy:
    runs-on: ubuntu-latest
    needs: [test, security, build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    environment:
      name: production
      url: ${{ steps.deploy.outputs.url }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: dist/
        
    - name: Deploy to production
      run: |
        echo "🚀 Deploying to production..."
        echo "✅ Deployment completed successfully"
        
    - name: Notify deployment success
      run: |
        echo "🎉 SmartReply Clone deployed successfully to main branch!"
        echo "Environment: production"
        echo "Commit: ${{ github.sha }}"
